#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 14 17:35:43 2017

@author: daviddoji

Solution to Project Euler problem 2

https://github.com/daviddoji/Project_Euler
"""


def compute():
    """
    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    Find the sum of all the even-valued terms in the sequence which do not
    exceed four million.
    """
    ans = 0
    x = 1
    y = 1
    z = x + y  # Because every third Fibonacci number is even
    while z <= 4000000:
        ans += z
        x = y + z
        y = z + x
        z = x + y
    return ans


if __name__ == "__main__":

    print(compute())
